apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-kind
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gitops-bootstrap
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default

  source:
    repoURL: https://github.com/Shinaayo07/simple-node-api.git
    targetRevision: main
    path: argocd/kind
    directory:
      recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5
