apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring-stack
spec:
  description: Lightweight in-cluster metrics/logs/traces stack (Prometheus, Loki, Tempo, Alloy, Grafana)

  sourceRepos:
    - https://github.com/Shinaayo07/simple-node-api.git
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts

  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: batch
      kind: Job
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: monitoring.coreos.com
      kind: "*"

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
