image:
  registry: docker.io
  repository: shina371/simple-node-api
  tag: "a1d79c393317b08417f4514e7acab28b9b16e141"
  digest: "sha256:e120de2787edfc096c5484055cc20f37e6a2c76aaa0d8ec8a2d81a0949c9d709"
externalSecrets:
  enabled: true
  provider: fake
  fakeValue: "local-dev-demo-value"
ingress:
  enabled: true
  className: nginx
  clusterIssuer: selfsigned-cluster-issuer
  host: customer-api.127.0.0.1.nip.io
  tlsSecretName: customer-api-tls
