nameOverride: ""
fullnameOverride: "customer-api"
namespace:
  create: true
  podSecurityStandard: restricted
image:
  registry: docker.io
  repository: shina371/simple-node-api
  tag: "66c141b7b37c649a3a473a7e1f7649a53920459c"
  digest: "sha256:e120de2787edfc096c5484055cc20f37e6a2c76aaa0d8ec8a2d81a0949c9d709"
  pullPolicy: IfNotPresent
replicaCount: 2
serviceAccount:
  create: true
  name: ""
  automount: false
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]
service:
  type: ClusterIP
  port: 3000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
probes:
  liveness:
    path: /health
  readiness:
    path: /ready
config:
  nodeEnv: production
  logLevel: info
  otelServiceName: customer-api
  otelExporterOtlpEndpoint: "http://tempo.monitoring.svc.cluster.local:4318/v1/traces"
ingress:
  enabled: true
  className: nginx
  clusterIssuer: letsencrypt-prod
  host: customer-api.example.com
  tlsSecretName: customer-api-tls
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  scaleDownStabilizationWindowSeconds: 300
podDisruptionBudget:
  minAvailable: 1
resourceQuota:
  requestsCpu: 500m
  requestsMemory: 512Mi
  limitsCpu: "2"
  limitsMemory: 1Gi
  pods: "5"
limitRange:
  defaultCpu: 500m
  defaultMemory: 256Mi
  defaultRequestCpu: 100m
  defaultRequestMemory: 128Mi
networkPolicy:
  enabled: true
  ingressNginx:
    namespaceLabel: ingress-nginx
    podLabel: ingress-nginx
  dns:
    namespaceLabel: kube-system
    podLabel: kube-dns
  tempo:
    namespaceLabel: monitoring
    podLabel: tempo
    port: 4318
  prometheus:
    namespaceLabel: monitoring
    podLabel: prometheus
serviceMonitor:
  enabled: true
  interval: 15s
dashboard:
  enabled: true
externalSecrets:
  enabled: true
  provider: azurekv
  workloadIdentity:
    clientId: "REPLACE_WITH_UAMI_CLIENT_ID"
    tenantId: "REPLACE_WITH_AZURE_TENANT_ID"
  keyVaultUrl: "https://REPLACE_WITH_KEY_VAULT_NAME.vault.azure.net"
  refreshInterval: 1h
  remoteKey: customer-api-demo-key
  fakeValue: "local-dev-demo-value"
