image:
  registry: docker.io
  repository: shina371/simple-node-api
  tag: "66c141b7b37c649a3a473a7e1f7649a53920459c"
  digest: "sha256:e120de2787edfc096c5484055cc20f37e6a2c76aaa0d8ec8a2d81a0949c9d709"
externalSecrets:
  enabled: true
  provider: fake
  fakeValue: "local-dev-demo-value"
ingress:
  enabled: true
  className: nginx
  clusterIssuer: selfsigned-cluster-issuer
  host: customer-api.127.0.0.1.nip.io
  tlsSecretName: customer-api-tls
