{{- if and .Values.externalSecrets.enabled (eq .Values.externalSecrets.provider "azurekv") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "customer-api.fullname" . }}-eso
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customer-api.labels" . | nindent 4 }}
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: {{ .Values.externalSecrets.workloadIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.externalSecrets.workloadIdentity.tenantId | quote }}
{{- end }}
