{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ include "customer-api.fullname" . }}-keyvault
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customer-api.labels" . | nindent 4 }}
spec:
  provider:
  {{- if eq .Values.externalSecrets.provider "fake" }}
    fake:
      data:
        - key: {{ .Values.externalSecrets.remoteKey | quote }}
          value: {{ .Values.externalSecrets.fakeValue | quote }}
  {{- else }}
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.externalSecrets.keyVaultUrl | quote }}
      tenantId: {{ .Values.externalSecrets.workloadIdentity.tenantId | quote }}
      serviceAccountRef:
        name: {{ include "customer-api.fullname" . }}-eso
  {{- end }}
{{- end }}
