{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "customer-api.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customer-api.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "customer-api.fullname" . }}-keyvault
    kind: SecretStore
  target:
    name: {{ include "customer-api.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: DEMO_API_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
{{- end }}
