apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "customer-api.fullname" . }}-quota
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customer-api.labels" . | nindent 4 }}
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory | quote }}
    pods: {{ .Values.resourceQuota.pods | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "customer-api.fullname" . }}-limits
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "customer-api.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.defaultCpu | quote }}
        memory: {{ .Values.limitRange.defaultMemory | quote }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequestCpu | quote }}
        memory: {{ .Values.limitRange.defaultRequestMemory | quote }}
